backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "source/images/works"
public_folder: "images/works"

collections:
  - name: "works"
    label: "Works"
    folder: "source/articles"
    create: true
    extension: "html.markdown"
    format: frontmatter
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
